window.BERYL_ROSTER = [
  {
    id: "beryl-roster-1-2",
    name: "ABELLADA, SEBASTIAN, JR ABIÑO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-3",
    name: "ARANEL, MATHEW JANRY, JELLY",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-4",
    name: "AUSTRIA, DELAN, ORGUIN",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-5",
    name: "BEATO, JUSHUA, MARIGONDON",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-6",
    name: "BELLUDO, XAVIER KHENN, ARIMADO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-7",
    name: "BERMILLO, EDWARD, MIRANDA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-8",
    name: "BRAVO, JEROME, CASABUENA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-9",
    name: "BRAVO, JUSTINE",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-10",
    name: "BRAVO, RAYMON, GALVEZ",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-11",
    name: "FORTADES, MARK DAVE, BENDECIO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-12",
    name: "GAVERIA, CLARENCE, ALA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-13",
    name: "GINETE, CIDREX LEONARD, AYCOCHO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-14",
    name: "JACOB, RASMAEL, REGONDOLA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-15",
    name: "JADIE, IAN JOSHUA, MORET",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-16",
    name: "LEOP, JOASH",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-17",
    name: "LLAMOSO, DEREK DAVE",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-18",
    name: "LORILLA, KHAIRO, BERZO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-19",
    name: "MARAVILLA, JACOB",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-20",
    name: "MEDALLADA, JOHN PAUL, ENVERZO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-21",
    name: "NAJE, JOSHUA, MANJARES",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-22",
    name: "NAPOLIS, MARK ZAIRON, BANANIA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-23",
    name: "PANITERCE, JOHN STEVEN, ATOLI",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-24",
    name: "REVALE, RHOI NICOLAS, ARTILLAGAS",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-25",
    name: "TABOSO, GEMUEL, LARCE",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-1-26",
    name: "TOLENTINO, RUBEN GABRIEL, BALDE",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-2",
    name: "AQUINO, MA. CELINA, BALLESTEROS",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-3",
    name: "ARINGO, JAYZEN TRICIA MARIE, RANESES",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-4",
    name: "ATUTUBO, SAMANTHA ZOEY, ACUÑA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-5",
    name: "BOLAÑOS, JILIAN, ANDAYA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-6",
    name: "BONGABONG, RHEALYN, MONTECASTRO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-7",
    name: "BUSTOS, ALSATIA NOELLE, YAP",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-8",
    name: "DITAL, CIARA JANE, PAR",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-9",
    name: "ESTALAR, HONEY MAE, BUMALAY",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-10",
    name: "MANDREZA, HANIEMAE, LLANTINO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-11",
    name: "MAPAGDALITA, SABEL, PEDRAGOSA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-12",
    name: "MIRANDA,SOPHIA RHAIN, REPOLLOSA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-13",
    name: "NACE, JAY ANN, DEL ROSARIO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-14",
    name: "NAVARRO, JERRY MAE, ABAD",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-15",
    name: "ORACION, MERYL ANGEL, ORIERA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-16",
    name: "ORAYAN, CHESKA, CAÑA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-17",
    name: "PUCHE, PAULINE KAYTH, SEVILLA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-18",
    name: "TEE, ANGEL, DESOLO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-19",
    name: "TOLEDO, GENNEL, ESCARTIN",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "beryl-roster-8-20",
    name: "YASOL, GINA REMS",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
];
